### PR TITLE
Refactor reconnection

### PR DESCRIPTION
**Pull request by FalseR20**
# Reconnection to sc-server

## How to test

Paste this python script

```python
import logging
import signal

from sc_client.client import connect, disconnect

root_logger = logging.getLogger()
root_logger.level = logging.DEBUG
root_logger.addHandler(logging.StreamHandler())

url = "ws://localhost:8090/ws_json"
connect(url, do_reconnect=True, reconnection_time=1.0)

root_logger.info("Press ^C to disconnect")
signal.signal(signal.SIGINT, lambda *_: root_logger.info("^C: disconnecting"))
signal.pause()

disconnect()
```

Now run it. In other terminal run/close sc-server and check logs. 
In any time press ^C (ctrl-C or close using IDE) and client will close connection.

### CODE REVIEW

**Comment by FallenChromium** [comment]
Potentially it would be better to re-establish connection on demand, i.e having a handler on ConnectionClosed or whatever is the exception in the sockets library. This way we will put less strain on sc-server if nothing is actually happening on the client-side, reduce log spam in sc-server.log and the while loop wouldn't emit an instruction every 2 seconds. Also, there's a small window for the connection to break between these 2 seconds and emit an exception in some sc-client method, which has ridiculously small probability but trust me, it'll happen someday 😂. So it's better to handle it at the exception level imo

**Comment by FalseR20** [comment]
> Potentially it would be better to re-establish connection on demand, i.e having a handler on ConnectionClosed or whatever is the exception in the sockets library. This way we will put less strain on sc-server if nothing is actually happening on the client-side, reduce log spam in sc-server.log and the while loop wouldn't emit an instruction every 2 seconds. Also, there's a small window for the connection to break between these 2 seconds and emit an exception in some sc-client method, which has ridiculously small probability but trust me, it'll happen someday joy. So it's better to handle it at the exception level imo

God damn bro... It's deep.
I'll try to fix this 2sec window.
But about exception: I think we need full refactoring of api part with new architecture and/or async usage.

**Comment by FalseR20** [comment]
I tried to close this 2 second window. If the client does not reconnect, it will wait. But if the connection is successful, it will check the connection without sleep
UPD: handling the exception next time

**Review by smousy — APPROVED** [review]

**Comment by FallenChromium** [comment]
🤯
What's the CPU usage of a while(true) if checks? That looks like a resource hog to me 🤔
Not sure what could be an elegant fix to this problem without a refactor though, so it's just a note rather than a request for change

**Comment by FalseR20** [comment]
I added one more sleep in reconnection to remove 100% load and add time window in while True. It looks scarier but works correctly

**Review by FallenChromium — APPROVED** [review]
LGTM! Though we will definitely have to come back to this problem and refactor the client to handle it better. Creating an issue about it would be great too.

**Review by MikhailSadovsky — APPROVED** [review]

**Comment by FalseR20** [comment]
All Chaos Emeralds collected!

**Pull request merged**
